<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>GARbro</AssemblyName>
    <RootNamespace>GARbro.Desktop</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="SoundFlow" Version="1.4.1" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(PkgSoundFlow)/runtimes/**/native/*" Link="runtimes/%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GARbro.Core/GARbro.Core.csproj" />
    <ProjectReference Include="../GARbro.Formats/GARbro.Formats.csproj" />
  </ItemGroup>
</Project>
