<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../GARbro.Core/GARbro.Core.csproj" />
    <ProjectReference Include="../GARbro.Formats/GARbro.Formats.csproj" />
    <ProjectReference Include="../GARbro.LegacyDataMigration/GARbro.LegacyDataMigration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../ArcFormats/Resources/Formats.dat" Link="Fixtures/Formats.dat" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
