<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>garbro-legacy-data-migration</AssemblyName>
    <RootNamespace>GARbro.LegacyDataMigration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.10" />
  </ItemGroup>
</Project>
